// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import http "net/http"
import io "io"
import mock "github.com/stretchr/testify/mock"
import pester "github.com/peernova-private/pester"
import url "net/url"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Do provides a mock function with given fields: req
func (_m *Client) Do(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EmbedHTTPClient provides a mock function with given fields: hc
func (_m *Client) EmbedHTTPClient(hc *http.Client) {
	_m.Called(hc)
}

// FormatError provides a mock function with given fields: e
func (_m *Client) FormatError(e pester.ErrEntry) string {
	ret := _m.Called(e)

	var r0 string
	if rf, ok := ret.Get(0).(func(pester.ErrEntry) string); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Get provides a mock function with given fields: _a0
func (_m *Client) Get(_a0 string) (*http.Response, error) {
	ret := _m.Called(_a0)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string) *http.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfig provides a mock function with given fields:
func (_m *Client) GetConfig() pester.Config {
	ret := _m.Called()

	var r0 pester.Config
	if rf, ok := ret.Get(0).(func() pester.Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pester.Config)
	}

	return r0
}

// GetErrLog provides a mock function with given fields:
func (_m *Client) GetErrLog() []pester.ErrEntry {
	ret := _m.Called()

	var r0 []pester.ErrEntry
	if rf, ok := ret.Get(0).(func() []pester.ErrEntry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pester.ErrEntry)
		}
	}

	return r0
}

// Head provides a mock function with given fields: _a0
func (_m *Client) Head(_a0 string) (*http.Response, error) {
	ret := _m.Called(_a0)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string) *http.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogErrCount provides a mock function with given fields:
func (_m *Client) LogErrCount() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// LogString provides a mock function with given fields:
func (_m *Client) LogString() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Post provides a mock function with given fields: _a0, bodyType, body
func (_m *Client) Post(_a0 string, bodyType string, body io.Reader) (*http.Response, error) {
	ret := _m.Called(_a0, bodyType, body)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) *http.Response); ok {
		r0 = rf(_a0, bodyType, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = rf(_a0, bodyType, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostForm provides a mock function with given fields: _a0, data
func (_m *Client) PostForm(_a0 string, data url.Values) (*http.Response, error) {
	ret := _m.Called(_a0, data)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, url.Values) *http.Response); ok {
		r0 = rf(_a0, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, url.Values) error); ok {
		r1 = rf(_a0, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetRetryOnHTTP429 provides a mock function with given fields: flag
func (_m *Client) SetRetryOnHTTP429(flag bool) {
	_m.Called(flag)
}

// Wait provides a mock function with given fields:
func (_m *Client) Wait() {
	_m.Called()
}
